#!/usr/bin/env python
"""Build the unified 1-year common-reference comparison artefacts."""

from __future__ import annotations

import csv
import json
import statistics
from pathlib import Path
from typing import Any

import typer

from mcp_quant_agent.eval.reasoning import (
    _segment_by_regime,
    compute_mcp_time_machine_audit,
    compute_pm_evidence_grounding,
)
from mcp_quant_agent.llm_telemetry import summarize_usage

app = typer.Typer(add_completion=False)


def _load_json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [
        json.loads(line)
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def _read_kv_summary(path: Path) -> dict[str, str]:
    rows = list(csv.DictReader(path.open(encoding="utf-8")))
    return {str(row["metric"]): str(row["value"]) for row in rows}


def _read_baselines(path: Path) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with path.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            parsed: dict[str, Any] = dict(row)
            for key, value in row.items():
                if key not in {"ticker", "strategy", "start_date", "end_date"}:
                    try:
                        parsed[key] = float(value)
                    except (TypeError, ValueError):
                        parsed[key] = value
            rows.append(parsed)
    return rows


def _fmt_pct(value: float, digits: int = 1) -> float:
    return round(float(value) * 100.0, digits)


def _fmt_float(value: Any, digits: int = 3) -> float:
    try:
        return round(float(value), digits)
    except (TypeError, ValueError):
        return 0.0


def _ci_text(ci: dict[str, Any]) -> str:
    return f"[{_fmt_float(ci.get('ci_lower', 0))}, {_fmt_float(ci.get('ci_upper', 0))}]"


def _latency_stats(decisions: list[dict[str, Any]]) -> dict[str, float]:
    vals = sorted(float(d.get("latency_ms") or 0.0) for d in decisions)
    if not vals:
        return {"p50_ms": 0.0, "p95_ms": 0.0}
    return {
        "p50_ms": round(statistics.median(vals), 1),
        "p95_ms": round(vals[min(len(vals) - 1, round((len(vals) - 1) * 0.95))], 1),
    }


def _financial_row(
    *,
    label: str,
    run_id: str,
    kind: str,
    metrics: dict[str, Any],
    sharpe_ci: dict[str, Any],
    n_decisions: int | str,
    errors: int | str = 0,
) -> dict[str, Any]:
    return {
        "label": label,
        "run_id": run_id,
        "kind": kind,
        "n_decisions": n_decisions,
        "n_errors_excluded": errors,
        "annualised_return_pct": _fmt_pct(metrics.get("annualised_return", 0.0)),
        "sharpe": _fmt_float(metrics.get("sharpe", 0.0)),
        "sharpe_ci": _ci_text(sharpe_ci),
        "max_drawdown_pct": _fmt_pct(metrics.get("max_drawdown", 0.0)),
        "turnover_pct": _fmt_float(metrics.get("turnover_pct", 0.0), 2),
        "cost_drag_bps": _fmt_float(metrics.get("cost_drag_bps", 0.0), 2),
    }


def _write_csv(path: Path, rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def _escape_tex(value: str) -> str:
    return value.replace("_", r"\_")


def _macro(name: str, value: str | int | float) -> str:
    if isinstance(value, int):
        return f"\\newcommand{{\\{name}}}{{{value}}}"
    if isinstance(value, float):
        return f"\\newcommand{{\\{name}}}{{{value}}}"
    return f"\\newcommand{{\\{name}}}{{{{{value}}}}}"


def _upsert_numbers_block(path: Path, lines: list[str]) -> None:
    start = "% COMMON-REFERENCE AUTOGENERATED START"
    end = "% COMMON-REFERENCE AUTOGENERATED END"
    block = "\n".join([start, *lines, end]) + "\n"
    if path.exists():
        text = path.read_text(encoding="utf-8")
        if start in text and end in text:
            before = text.split(start, maxsplit=1)[0]
            after = text.split(end, maxsplit=1)[1].lstrip("\n")
            path.write_text(before + block + after, encoding="utf-8")
            return
        path.write_text(text.rstrip() + "\n\n" + block, encoding="utf-8")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(block, encoding="utf-8")


def _reasoning_rows(
    *,
    label: str,
    manifest: dict[str, Any],
    pm: bool = False,
    decisions: list[dict[str, Any]] | None = None,
) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    prefix = "pm_" if pm else ""
    details = (
        manifest.get("pm_faithfulness_details")
        if pm
        else manifest.get("faithfulness_v2_details")
    ) or {}
    pm_overall_grounding = (manifest.get("pm_evidence_grounding") or {}).get(
        "pm_evidence_grounding",
        manifest.get("grounding_overall", 0.0),
    )
    rows.append(
        {
            "label": label,
            "regime": "overall",
            "n_decisions": manifest.get("n_decisions", 0),
            "faithfulness": _fmt_float(
                manifest.get(f"{prefix}faithfulness", manifest.get("faithfulness_v2", 0))
            ),
            "faithfulness_strict": _fmt_float(
                manifest.get(
                    f"{prefix}faithfulness_strict",
                    manifest.get("faithfulness_v2_strict", 0),
                )
            ),
            "n_scoreable": details.get("n_scoreable", ""),
            "n_faithful": details.get("n_faithful", ""),
            "n_unfaithful": details.get("n_unfaithful", ""),
            "n_constrained": details.get("n_constrained", ""),
            "grounding": _fmt_float(
                pm_overall_grounding if pm else manifest.get("grounding_overall", 0.0)
            ),
        }
    )
    pm_grounding_by_regime: dict[str, float] = {}
    if pm and decisions is not None:
        non_error = [d for d in decisions if not d.get("is_error", False)]
        for regime, decs in _segment_by_regime(non_error).items():
            if regime == "__warmup__":
                continue
            pm_grounding_by_regime[regime] = float(
                compute_pm_evidence_grounding(decs).get("pm_evidence_grounding", 0.0)
            )
    for regime, data in sorted((manifest.get("reasoning_by_regime") or {}).items()):
        rows.append(
            {
                "label": label,
                "regime": regime,
                "n_decisions": data.get("n_decisions", 0),
                "faithfulness": _fmt_float(
                    data.get("pm_faithfulness" if pm else "faithfulness", 0.0)
                ),
                "faithfulness_strict": _fmt_float(
                    data.get(
                        "pm_faithfulness_strict" if pm else "faithfulness_strict",
                        0.0,
                    )
                ),
                "n_scoreable": data.get("n_scoreable", ""),
                "n_faithful": data.get("n_faithful", ""),
                "n_unfaithful": data.get("n_unfaithful", ""),
                "n_constrained": data.get("n_constrained", ""),
                "grounding": _fmt_float(
                    pm_grounding_by_regime.get(regime, data.get("grounding", 0.0))
                    if pm
                    else data.get("grounding", 0.0)
                ),
            }
        )
    return rows


def _audit_run(
    *,
    label: str,
    decisions: list[dict[str, Any]],
    manifest: dict[str, Any],
    expected_decisions: int,
    expected_tickers: int,
    pm: bool = False,
) -> dict[str, Any]:
    non_error = [
        d for d in decisions
        if not d.get("is_error", False) and str(d.get("action", "")) != "error"
    ]
    segments = _segment_by_regime(non_error)
    n_warmup = len(segments.get("__warmup__", []))
    n_segmented = sum(len(v) for v in segments.values())
    time_audit = manifest.get("mcp_time_machine_audit") or compute_mcp_time_machine_audit(
        non_error
    )
    audit: dict[str, Any] = {
        "label": label,
        "n_decisions_manifest": manifest.get("n_decisions"),
        "n_decisions_jsonl": len(decisions),
        "n_errors_excluded": len(decisions) - len(non_error),
        "expected_decisions": expected_decisions,
        "expected_non_error_decisions": expected_decisions
        - (len(decisions) - len(non_error)),
        "n_warmup_excluded": n_warmup,
        "regime_rows_sum": n_segmented,
        "mcp_time_machine_pass": bool(time_audit.get("pass")),
        "mcp_time_machine_violations": int(time_audit.get("n_violations", 0)),
        "mcp_time_machine_checks": int(time_audit.get("n_timestamp_checks", 0)),
        "pass": True,
    }
    if pm:
        n_reports = sum(len(d.get("reports") or []) for d in non_error)
        audit["n_reports"] = n_reports
        audit["expected_reports"] = len(non_error) * expected_tickers * 3
    audit["pass"] = (
        len(decisions) == expected_decisions
        and len(non_error) == audit["expected_non_error_decisions"]
        and n_warmup == 0
        and n_segmented == len(non_error)
        and bool(time_audit.get("pass"))
        and int(time_audit.get("n_violations", 0)) == 0
        and (not pm or audit.get("n_reports") == audit.get("expected_reports"))
    )
    return audit


@app.command()
def main(
    single_run_id: str = typer.Option(..., help="Single-agent run id."),
    pm_run_id: str = typer.Option(..., help="PM multi-agent run id."),
    baseline_csv: Path = typer.Option(..., help="CSV from scripts/run_baselines.py."),
    output_dir: Path = typer.Option(
        Path("results/common_reference_2023_aapl_msft_nvda"),
        help="Output directory for comparison artefacts.",
    ),
    numbers_tex: Path = typer.Option(
        Path("thesis/results/numbers.tex"),
        help="Thesis numbers.tex to update with common-reference macros.",
    ),
) -> None:
    """Write comparison CSV/JSON artefacts and update thesis macros."""
    single_manifest = _load_json(
        Path("results") / single_run_id / "bounded_eval_manifest.json"
    )
    pm_manifest = _load_json(Path("results") / pm_run_id / "pm_multiday_manifest.json")
    pm_summary = _read_kv_summary(Path("results") / pm_run_id / "summary.csv")
    single_decisions = _load_jsonl(Path("runs") / single_run_id / "decisions.jsonl")
    pm_decisions = _load_jsonl(Path("runs") / pm_run_id / "decisions.jsonl")
    baseline_rows = _read_baselines(baseline_csv)

    tickers = [str(t) for t in single_manifest.get("tickers", [])]
    start = str(single_manifest.get("start"))
    end = str(single_manifest.get("end"))
    if pm_manifest.get("tickers") != single_manifest.get("tickers"):
        raise typer.BadParameter("Single-agent and PM tickers differ.")
    if str(pm_manifest.get("start")) != start or str(pm_manifest.get("end")) != end:
        raise typer.BadParameter("Single-agent and PM windows differ.")

    single_metrics = single_manifest.get("metrics", {})
    pm_metrics = pm_manifest.get("metrics", {})
    single_ci = single_manifest.get("sharpe_ci", {})
    pm_ci = {
        "ci_lower": float(pm_summary.get("sharpe_ci_low", 0.0)),
        "ci_upper": float(pm_summary.get("sharpe_ci_high", 0.0)),
    }

    financial_rows = [
        _financial_row(
            label="Single Agent",
            run_id=single_run_id,
            kind="single_agent",
            metrics=single_metrics,
            sharpe_ci=single_ci,
            n_decisions=single_manifest.get("n_decisions", 0),
            errors=sum(1 for d in single_decisions if str(d.get("action")) == "error"),
        ),
        _financial_row(
            label="PM Multi-Agent",
            run_id=pm_run_id,
            kind="pm_multi_agent",
            metrics=pm_metrics,
            sharpe_ci=pm_ci,
            n_decisions=pm_manifest.get("n_decisions", 0),
            errors=sum(1 for d in pm_decisions if d.get("is_error", False)),
        ),
    ]
    for row in baseline_rows:
        if row.get("ticker") != "EQUAL-WT":
            continue
        financial_rows.append(
            _financial_row(
                label=f"Baseline: {row['strategy']}",
                run_id=Path(baseline_csv).stem,
                kind="baseline_equal_weight",
                metrics=row,
                sharpe_ci={
                    "ci_lower": row.get("sharpe_ci_lower", 0.0),
                    "ci_upper": row.get("sharpe_ci_upper", 0.0),
                },
                n_decisions="n/a",
                errors="n/a",
            )
        )

    reasoning_rows = [
        *_reasoning_rows(label="Single Agent", manifest=single_manifest, pm=False),
        *_reasoning_rows(
            label="PM Multi-Agent",
            manifest=pm_manifest,
            pm=True,
            decisions=pm_decisions,
        ),
    ]

    single_usage = summarize_usage(Path("runs") / single_run_id / "llm_usage.jsonl")
    pm_usage = summarize_usage(Path("runs") / pm_run_id / "llm_usage.jsonl")
    single_latency = _latency_stats(single_decisions)
    pm_latency = _latency_stats(pm_decisions)
    total_wall = (
        float(single_usage.get("wall_clock_seconds", 0.0))
        + float(pm_usage.get("wall_clock_seconds", 0.0))
    )
    tech = {
        "single_agent": {
            **single_usage,
            "decision_latency": single_latency,
            "error_rate": financial_rows[0]["n_errors_excluded"]
            / max(int(single_manifest.get("n_decisions", 1)), 1),
            "decisions_per_minute": round(
                int(single_manifest.get("n_decisions", 0))
                / max(float(single_usage.get("wall_clock_seconds", 0.0)) / 60.0, 1e-9),
                3,
            ),
        },
        "pm_multi_agent": {
            **pm_usage,
            "decision_latency": pm_latency,
            "error_rate": financial_rows[1]["n_errors_excluded"]
            / max(int(pm_manifest.get("n_decisions", 1)), 1),
            "decisions_per_minute": round(
                int(pm_manifest.get("n_decisions", 0))
                / max(float(pm_usage.get("wall_clock_seconds", 0.0)) / 60.0, 1e-9),
                3,
            ),
        },
        "combined": {
            "api_calls": int(single_usage.get("n_api_calls", 0))
            + int(pm_usage.get("n_api_calls", 0)),
            "cache_hits": int(single_usage.get("n_cache_hits", 0))
            + int(pm_usage.get("n_cache_hits", 0)),
            "total_tokens": int(single_usage.get("total_tokens", 0))
            + int(pm_usage.get("total_tokens", 0)),
            "incremental_cost_usd": round(
                float(single_usage.get("incremental_cost_usd", 0.0))
                + float(pm_usage.get("incremental_cost_usd", 0.0)),
                6,
            ),
            "wall_clock_seconds": round(total_wall, 1),
        },
    }

    expected_single = len(tickers) * int(pm_manifest.get("n_decisions", 0))
    audits = [
        _audit_run(
            label="Single Agent",
            decisions=single_decisions,
            manifest=single_manifest,
            expected_decisions=expected_single,
            expected_tickers=len(tickers),
        ),
        _audit_run(
            label="PM Multi-Agent",
            decisions=pm_decisions,
            manifest=pm_manifest,
            expected_decisions=int(pm_manifest.get("n_decisions", 0)),
            expected_tickers=len(tickers),
            pm=True,
        ),
    ]

    output_dir.mkdir(parents=True, exist_ok=True)
    _write_csv(output_dir / "comparison_financial.csv", financial_rows)
    _write_csv(output_dir / "reasoning_by_regime.csv", reasoning_rows)
    (output_dir / "technical_metrics.json").write_text(
        json.dumps(tech, indent=2, default=str),
        encoding="utf-8",
    )
    (output_dir / "arithmetic_audit.json").write_text(
        json.dumps(audits, indent=2, default=str),
        encoding="utf-8",
    )

    single_row = financial_rows[0]
    pm_row = financial_rows[1]
    baseline_by_strategy = {
        str(row["label"]).replace("Baseline: ", ""): row
        for row in financial_rows
        if row["kind"] == "baseline_equal_weight"
    }
    total_cost = tech["combined"]["incremental_cost_usd"]
    checks = sum(int(a["mcp_time_machine_checks"]) for a in audits)
    violations = sum(int(a["mcp_time_machine_violations"]) for a in audits)
    block_lines = [
        "% 1-year common-reference run; generated by scripts/summarize_common_reference.py",
        _macro("commonRunLabel", "1-year common-reference run"),
        _macro("commonStart", start),
        _macro("commonEnd", end),
        _macro("commonUniverse", ", ".join(tickers)),
        _macro("commonSingleRunId", rf"\texttt{{{_escape_tex(single_run_id)}}}"),
        _macro("commonPmRunId", rf"\texttt{{{_escape_tex(pm_run_id)}}}"),
        _macro("commonNTradingDays", pm_manifest.get("n_decisions", 0)),
        _macro("commonSingleDecisions", single_manifest.get("n_decisions", 0)),
        _macro("commonPmDecisions", pm_manifest.get("n_decisions", 0)),
        _macro("commonPmErrors", financial_rows[1]["n_errors_excluded"]),
        _macro("commonPmErrorRate", round(tech["pm_multi_agent"]["error_rate"], 4)),
        _macro("commonSingleAnnReturn", single_row["annualised_return_pct"]),
        _macro("commonSingleSharpe", single_row["sharpe"]),
        _macro("commonSingleSharpeCI", single_row["sharpe_ci"]),
        _macro("commonSingleMaxDD", single_row["max_drawdown_pct"]),
        _macro("commonSingleTurnover", single_row["turnover_pct"]),
        _macro("commonSingleCostDrag", single_row["cost_drag_bps"]),
        _macro("commonPmAnnReturn", pm_row["annualised_return_pct"]),
        _macro("commonPmSharpe", pm_row["sharpe"]),
        _macro("commonPmSharpeCI", pm_row["sharpe_ci"]),
        _macro("commonPmMaxDD", pm_row["max_drawdown_pct"]),
        _macro("commonPmTurnover", pm_row["turnover_pct"]),
        _macro("commonPmCostDrag", pm_row["cost_drag_bps"]),
        _macro("commonSingleFaith", reasoning_rows[0]["faithfulness"]),
        _macro("commonSingleFaithStrict", reasoning_rows[0]["faithfulness_strict"]),
        _macro("commonSingleGrounding", reasoning_rows[0]["grounding"]),
        _macro("commonPmFaith", reasoning_rows[len(single_manifest.get("reasoning_by_regime", {})) + 1]["faithfulness"]),
        _macro("commonPmFaithStrict", reasoning_rows[len(single_manifest.get("reasoning_by_regime", {})) + 1]["faithfulness_strict"]),
        _macro("commonPmGrounding", reasoning_rows[len(single_manifest.get("reasoning_by_regime", {})) + 1]["grounding"]),
        _macro("commonTimeMachineViolations", f"{violations}\\,/\\,{checks}"),
        _macro("commonSingleApiCalls", tech["single_agent"]["n_api_calls"]),
        _macro("commonPmApiCalls", tech["pm_multi_agent"]["n_api_calls"]),
        _macro("commonTotalTokens", tech["combined"]["total_tokens"]),
        _macro("commonTotalCost", rf"\${total_cost:.4f}"),
        _macro("commonWallClockMinutes", round(total_wall / 60.0, 1)),
    ]
    for strategy, prefix in [
        ("buy_and_hold", "Bh"),
        ("momentum_ts", "Mom"),
        ("mean_reversion_bb", "Mr"),
    ]:
        row = baseline_by_strategy.get(strategy)
        if not row:
            continue
        block_lines.extend(
            [
                _macro(f"common{prefix}AnnReturn", row["annualised_return_pct"]),
                _macro(f"common{prefix}Sharpe", row["sharpe"]),
                _macro(f"common{prefix}SharpeCI", row["sharpe_ci"]),
                _macro(f"common{prefix}MaxDD", row["max_drawdown_pct"]),
                _macro(f"common{prefix}Turnover", row["turnover_pct"]),
                _macro(f"common{prefix}CostDrag", row["cost_drag_bps"]),
            ]
        )
    _upsert_numbers_block(numbers_tex, block_lines)

    typer.echo(f"Financial comparison: {output_dir / 'comparison_financial.csv'}")
    typer.echo(f"Reasoning by regime: {output_dir / 'reasoning_by_regime.csv'}")
    typer.echo(f"Technical metrics: {output_dir / 'technical_metrics.json'}")
    typer.echo(f"Arithmetic audit: {output_dir / 'arithmetic_audit.json'}")
    typer.echo(f"numbers.tex updated: {numbers_tex}")
    if not all(a["pass"] for a in audits):
        raise typer.Exit(2)


if __name__ == "__main__":
    app()
